# Apache Ignite
ignite:
    -   name: igniteServerBean01
        serverBinary: /etc/apache-ignite-2.10.0/bin/ignite.sh
        confFile: /etc/apache-ignite/config/ignite-config.xml
        args: ""
        bootUpTimeMs: 3000
        tls:
            local_cert: /path/to/client/cert
            cafile: /path/to/ca/file
            local_pk: /path/to/key/file
        userName: a
        password: b


# Redis
redis:
    -   name: redisServerBean01
        serverBinary: /usr/local/bin/redis-server
        confFile: /etc/redis/redis.conf
        bootUpTimeMs: 300
        args: ""

# Memcached
memcached:
    -   name: memcachedBean01
        serverBinary: /usr/bin/memcached
        host: 127.0.0.1
        port: 11211
        udpPort: 0
        unixSocket: a
        pidfile: "/var/run/memcached_1.pid"
        args: "-u memcached"
        bootUpTimeMs: 300

# Hazelcast
hazelcast:
    -   name: hazelcastBean01
        serverBinary: etc/hazelcast-4.2.1/bin/start.sh
        confFile: /etc/hazelcast/config/hazelcast.xml
        bootUpTimeMs: 300
        args: ""
